# Generated by Django 2.2.26 on 2022-01-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220126_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAdmin',
        ),
    ]
